repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: prettier --write --ignore-unknown
        additional_dependencies:
          - prettier@3.8.3
        files: \.(md|markdown|ya?ml|json)$
        exclude: ^(uv\.lock|.*\.dvc)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
